### ISSUE TITLE
Quickstart documentation issues

### ISSUE THREAD

**Issue by jmseigneur** [neo-project/neo-blockchain-toolkit#2]
The quickstart documentation doesn't seem to have been updated based on the new code that has been committed. For example, my students had to use .NET Core 3+ SDK because it couldn't work anymore with .NET Core 2.2 SDK. 

Some NEO-Express commands have been changed, for example, "neo-express show gas" doesn't exist anymore and has been replaced by new options that we have been able to find out even if the documentation is not up to date. More importantly, "neo-express contract import" doesn't exist anymore and we haven't found yet the new option or method to import. Any solution to know how to import without "neo-express contract import" would be appreciated because we are stuck at this step.

**Comment by devhawk** [comment]
thanks for filing the issue @jmseigneur. We just shipped the new version and the docs haven't all been updated yet. 

Note, we are pretty consistent about keeping the [changelog](https://github.com/neo-project/neo-express/blob/master/changelog.md) up to date. That's not an good excuse for out of date docs - but at least it's a workaround for the future. 

To your two specifics questions:

- Changed `show gas` command to `show unclaimed` to match
  [RpcSystemAssetTracker](https://github.com/neo-project/neo-plugins/tree/b5388d753a2da1d59583dd9c66835e29ca7fd6f3/RpcSystemAssetTracker)
  [`getunclaimed`](https://docs.neo.org/docs/en-us/reference/rpc/latest-version/api/getunclaimed.html)
- Removed `contract import` command. `contract deploy` now accepts a path to a Neo VM .avm file,
  a path to a directory containing the .avm file, or a contract short name for a previously deployed
  smart contract.

**Comment by devhawk** [comment]
updated quickstart in commit [669af59cf57e501a234a2ddf6223ea039ae4ca2f](https://github.com/neo-project/neo-blockchain-toolkit/commit/669af59cf57e501a234a2ddf6223ea039ae4ca2f). Closing this issue. @jmseigneur, please open a new issue if you feel that the updated quickstart is still incorrect.
