### ISSUE TITLE
Neo express vscode creation form looks strange

### ISSUE THREAD

**Issue by vpereira** [neo-project/neo-blockchain-toolkit#21]
I'm not sure if that's the right tracker, but trying to create a new instance of Neo Express,  doesn't work. The form looks wrong comparing with all tutorials that I saw

![neo-express](https://user-images.githubusercontent.com/37418/116790698-0768a380-aab6-11eb-9f26-566e7a5a9cff.png)

**Comment by vpereira** [comment]
vpereira@LAPTOP-OVBVMBCA:~/blockchain/HelloWorld> neo-express --version
1.1.28+31a43c3153
vpereira@LAPTOP-OVBVMBCA:~/blockchain/HelloWorld>

**Comment by zlewe** [comment]
Are you trying to create instance for Neo 2 or Neo 3?
If it is the latter the tool is in the 'N3' tab below the Neo logo. I assume those tutorials you saw are probably N3 tutorials.

**Comment by vpereira** [comment]
Hi   @zlewe, thank you for your answer!

I'm following this tutorial https://www.youtube.com/watch?v=sbt6HzD5Avs&t=1852s

That's how their vscode neo extension "create looks like":

![vscode-neo-express](https://user-images.githubusercontent.com/37418/116803974-788e7200-ab1b-11eb-8559-2eb51010e0be.png)

Thats mine again for comparsion:
![neo-express](https://user-images.githubusercontent.com/37418/116803995-aa073d80-ab1b-11eb-83bf-52f0c84f421c.png)

if you see looks like mine has no javascript and css applied. 

The N3 vscode integration is working fine. 
The `neo-express` cli I was able to create my private blockchain without issues.

**Comment by zlewe** [comment]
You might want to follow the updated tutorials here because Neo is going to migrate to Neo 3 very soon unless you have very specific reasons to develop on Neo 2:
[](https://ngdenterprise.com/neo-tutorials/index.html)

**Comment by vpereira** [comment]
Nice @zlewe , thank you for your help. I'm evaluating NEO to use in a project and I'm looking for good documentation/tutorials to make sure that the team is able to learn it. I will close this issue for now, thanks!

**Comment by zlewe** [comment]
Only the preview version: [https://www.nuget.org/packages/Neo.Express/2.0.23-preview](https://www.nuget.org/packages/Neo.Express/2.0.23-preview)
Which will also be automatically installed by Neo Blockchain Toolkit extension in VS Code.

**Comment by devhawk** [comment]
@vpereira the 1.x version of neo express works for neo legacy, the 2.x version works for neo n3
