### ISSUE TITLE
Please add instruction on how to specify three contract properties

### ISSUE THREAD

**Issue by wanglongfei88** [neo-project/neo-blockchain-toolkit#3]
When we deploy a contract to Neo, we need to specify three properties like, storage, payable and dynamic invoke. 

In neo contract template, we can specify those properties using Features assembly attribute. For example:
```
[assembly: Features(ContractPropertyState.HasStorage)]
```

but how do we specify three properties at the same time? Can you please add some guide about this?

Thank you.

**Comment by devhawk** [comment]
As per [official docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/enum#enumeration-types-as-bit-flags), Flags enums like `ContractPropertyState` can be combined with [bitwise logical operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators#enumeration-logical-operators).

```
[assembly: Features(ContractPropertyState.HasStorage 
    | ContractPropertyState.HasDynamicInvoke
    | ContractPropertyState.Payable)]

```
